Carga del fichero json con los username de Discogs y elimininaci√≥n de duplicados para buscar sus ratings.

In [8]:
import pandas as pd

In [9]:
usernameRatingsCSV = '../TFM Files/usernameRatingsMerged.csv'

dfRatings = pd.read_csv(usernameRatingsCSV)
dfRatings

                user_id  master_id  rating
0       andygrayrecords    2336028       5
1       andygrayrecords   12579831       5
2               DarreLP    5018675       5
3               DarreLP    9436063       5
4               DarreLP    5423437       5
5               DarreLP     214559       5
6               DarreLP    5846974       5
7               DarreLP   11151270       5
8               DarreLP    2276858       5
9               DarreLP    8867485       5
10              DarreLP    8867510       5
11              DarreLP     377537       5
12              DarreLP    1445801       5
13              DarreLP    1581600       5
14              DarreLP   10844664       5
15              DarreLP   10170246       5
16              DarreLP    1511099       5
17              DarreLP    7375186       5
18              DarreLP    5612436       5
19              DarreLP    7923063       5
20              DarreLP    5097003       5
21              DarreLP   11724844       5
22              DarreLP     112376       5
23              DarreLP    2585893       5
24              DarreLP    4655640       5
25              DarreLP    8039703       5
26              DarreLP    1382899       5
27              DarreLP   11544153       5
28              DarreLP   12225406       5
29              DarreLP    2515439       5
...                 ...        ...     ...
379922      Showbiz_Kid    1961779       2
379923      Showbiz_Kid    7422787       2
379924      Showbiz_Kid    3185165       2
379925      Showbiz_Kid    7088158       2
379926      Showbiz_Kid    5640587       2
379927      Showbiz_Kid    2706716       2
379928      Showbiz_Kid    5677799       2
379929      Showbiz_Kid   13346604       2
379930      Showbiz_Kid    3776495       2
379931      Showbiz_Kid    4151704       2
379932      Showbiz_Kid    2326420       2
379933      Showbiz_Kid    2096927       2
379934      Showbiz_Kid    5543632       2
379935      Showbiz_Kid    1449591       2
379936      Showbiz_Kid    6612442       2
379937      Showbiz_Kid    6043965       2
379938      Showbiz_Kid    1532262       2
379939      Showbiz_Kid    5234848       2
379940      Showbiz_Kid    2886980       2
379941      Showbiz_Kid    2511433       2
379942      Showbiz_Kid    8291637       2
379943      Showbiz_Kid    1304226       2
379944      Showbiz_Kid    3622532       2
379945      Showbiz_Kid   11365972       2
379946      Showbiz_Kid    7538406       2
379947        folkerman   13729175       5
379948      craigandkim    4749664       4
379949      craigandkim    5278669       4
379950      craigandkim    5774203       2
379951      craigandkim     669084       1

[379952 rows x 3 columns]

In [10]:
print("N√∫mero de usuarios (con repetidos): ", dfRatings.count())
dfUsersRatings = dfRatings.drop_duplicates("user_id")
print("N√∫mero de usuarios: ", dfUsersRatings.count())

N√∫mero de usuarios (con repetidos):  user_id      379952
master_id    379952
rating       379952
dtype: int64
N√∫mero de usuarios:  user_id      535
master_id    535
rating       535
dtype: int64

In [11]:
print("N√∫mero de items (con repetidos): ", dfRatings.count())
dfItemsRatings = dfRatings.drop_duplicates("master_id")
print("N√∫mero de items: ", dfItemsRatings.count())

N√∫mero de items (con repetidos):  user_id      379952
master_id    379952
rating       379952
dtype: int64
N√∫mero de items:  user_id      311570
master_id    311570
rating       311570
dtype: int64

<p>La cantidad de diferentes items es demasiado grande para calcularla con un equipo no preparado para calcular grandes dimensiones.</p>
<p>Por eso, se van a utilizar los ratings que se pueden encontrar en los datos utilizados por el filtrado de contenido.</p>

In [18]:
fullJsonFile = '../TFM Files/CNT2.2 - dataScaled/dataScaled.json'

scaledData = pd.read_json(path_or_buf=fullJsonFile, lines=True)
    
scaledData

,master_id,scaledFeatures,title
0,81137,"{'type': 1, 'values': [0.133408535931401, -0.7...",Greenbank Drive
1,81640,"{'type': 1, 'values': [0.10568112353641101, 0....",Dancing On The Couch
2,82039,"{'type': 1, 'values': [0.11030235893557601, -0...",We're Rocking The Planet
3,82494,"{'type': 1, 'values': [0.133408535931401, -0.8...",It Takes Me Higher
4,83907,"{'type': 1, 'values': [0.082574946540585, -0.0...",Bitter Sweet
5,87426,"{'type': 1, 'values': [0.11030235893557601, 0....",Sussex Drive
6,90803,"{'type': 1, 'values': [0.124166065133071, 0.22...",Hollow Man (Original Motion Picture Soundtrack)
7,94241,"{'type': 1, 'values': [0.10568112353641101, -0...","Chicas, Chicas, Chicas"
8,97214,"{'type': 1, 'values': [0.11954482973390601, 0....",Extensions
9,98178,"{'type': 1, 'values': [0.11030235893557601, 0....",Alex Party
10,98328,"{'type': 1, 'values': [0.11954482973390601, -0...",Barry Blue
11,98999,"{'type': 1, 'values': [0.138029771330567, -0.7...",Somebody
12,99399,"{'type': 1, 'values': [0.10568112353641101, -0...",The Invincible Sex
13,100143,"{'type': 1, 'values': [0.133408535931401, -0.6...",Don't You Try It
14,100288,"{'type': 1, 'values': [0.09643865273808101, 0....",Turn-A-Round
15,102367,"{'type': 1, 'values': [0.128787300532236, -0.8...",Sick Of It
16,102515,"{'type': 1, 'values': [0.133408535931401, -0.7...",Sir Duke / He's Misstra Know-It-All
17,102858,"{'type': 1, 'values': [0.11954482973390601, 0....",Cha Cha
18,103368,"{'type': 1, 'values': [0.050226298746430004, -...",Rusty Acid
19,105384,"{'type': 1, 'values': [0.08719618193975001, -0...",Morning Light
20,106899,"{'type': 1, 'values': [0.10568112353641101, 0....",The Misery Index: Notes From The Plague Years
21,108158,"{'type': 1, 'values': [0.14265100672973202, 0....",Marcus Garvey/Garvey's Ghost
22,112042,"{'type': 1, 'values': [0.064090004943925, 0.17...",A Blues For Buddha
23,112761,"{'type': 1, 'values': [0.14265100672973202, 0....",De Pre Historie 1960
24,115085,"{'type': 1, 'values': [0.14265100672973202, -0...",Reveraze / Sleeping Beauty
25,115933,"{'type': 1, 'values': [0.09643865273808101, 0....",No Code
26,116920,"{'type': 1, 'values': [0.09643865273808101, -0...",Baby I Need Your Lovin'
27,117140,"{'type': 1, 'values': [0.124166065133071, 0.34...",Linus & Lucy - The Music Of Vince Guaraldi
28,117496,"{'type': 1, 'values': [0.133408535931401, 0.00...",You Got It
29,118616,"{'type': 1, 'values': [0.091817417338916, -0.5...",Paper Chaser
...,...,...,...
69925,48582,"{'type': 1, 'values': [0.124166065133071, 0.82...",Enforcers (Above The Law)
69926,50593,"{'type': 1, 'values': [0.138029771330567, -0.6...",Fashion Slam
69927,51260,"{'type': 1, 'values': [0.138029771330567, -0.8...",It's Nasty
69928,52439,"{'type': 1, 'values': [0.114923594334741, 0.44...",Absolute Benson
69929,52837,"{'type': 1, 'values': [0.091817417338916, -0.4...",Post Post-Modern Man
69930,53185,"{'type': 1, 'values': [0.133408535931401, -0.7...",A Little Less Conversation
69931,55341,"{'type': 1, 'values': [0.101059888137246, -0.5...",Windowshopping
69932,55587,"{'type': 1, 'values': [0.138029771330567, -0.1...",Dos
69933,55948,"{'type': 1, 'values': [0.091817417338916, -0.7...",The Grand Hour
69934,56235,"{'type': 1, 'values': [0.124166065133071, 0.48...",Rump Comp Volume One
69935,56896,"{'type': 1, 'values': [0.138029771330567, -0.2...",The In Crowd
69936,58320,"{'type': 1, 'values': [0.11954482973390601, -0...",Country Life
69937,60238,"{'type': 1, 'values': [0.124166065133071, -0.0...",Chet
69938,62007,"{'type': 1, 'values': [0.124166065133071, -0.4...",Plutonium
69939,62374,"{'type': 1, 'values': [0.133408535931401, -0.2...",Omen III (Remixes)
69940,65279,"{'type': 1, 'values': [0.082574946540585, -0.8...",Him Or Me
69941,67142,"{'type': 1, 'values': [0.10568112353641101, 0....",Gas Food Lodging (Original Soundtrack)
69942,67705,"{'type': 1, 'values': [0.133408535931401, -0.2...",Guantanamera
69943,68532,"{'type': 1, 'values': [0.138029771330567, -0.3...",Part 3
69944,68924,"{'type': 1, 'values': [0.082574946540585, 0.56...",Big Bang Boogie
69945,69747,"{'type': 1, 'values': [0.10568112353641101, -0...",Soudain
69946,72190,"{'type': 1, 'values': [0.10568112353641101, -0...",The Peel Sessions
69947,72521,"{'type': 1, 'values': [0.10568112353641101, -0...",Everything But The Girl vs. Drum 'N' Bass
69948,75131,"{'type': 1, 'values': [0.08719618193975001, -0...",Crazy Rhythm
69949,76795,"{'type': 1, 'values': [0.128787300532236, -0.8...",Let Go The Line
69950,76940,"{'type': 1, 'values': [0.101059888137246, 0.80...",2Faces
69951,77609,"{'type': 1, 'values': [0.138029771330567, 0.03...",Boogie With Canned Heat
69952,78994,"{'type': 1, 'values': [0.138029771330567, -0.7...",Check It Up
69953,80004,"{'type': 1, 'values': [0.124166065133071, 0.10...",Looking At You
69954,80626,"{'type': 1, 'values': [0.138029771330567, 0.24...",Goodbye Jumbo

In [28]:
master_idList = scaledData["master_id"].tolist()
master_idList

[81137,
 81640,
 82039,
 82494,
 83907,
 87426,
 90803,
 94241,
 97214,
 98178,
 98328,
 98999,
 99399,
 100143,
 100288,
 102367,
 102515,
 102858,
 103368,
 105384,
 106899,
 108158,
 112042,
 112761,
 115085,
 115933,
 116920,
 117140,
 117496,
 118616,
 118871,
 120164,
 120362,
 121268,
 121426,
 123197,
 126104,
 127569,
 129229,
 129402,
 129405,
 131514,
 132449,
 133087,
 133961,
 136993,
 137945,
 140189,
 140542,
 141119,
 143215,
 146365,
 147311,
 147906,
 149089,
 152323,
 154519,
 156382,
 156614,
 156881,
 157607,
 162885,
 163597,
 166015,
 171718,
 172101,
 175845,
 175854,
 176725,
 178211,
 180100,
 181216,
 184268,
 185256,
 189018,
 190107,
 191863,
 192427,
 193343,
 194323,
 197073,
 197651,
 200643,
 202552,
 203294,
 204063,
 204580,
 208448,
 209599,
 211584,
 212370,
 214399,
 216312,
 219535,
 226871,
 227498,
 227909,
 228958,
 233343,
 233594,
 234695,
 237609,
 242268,
 243357,
 244375,
 244578,
 244769,
 244956,
 245341,
 252391,
 257918,
 265935,
 279781,
 298580,
 299910,
 300195,
 304940,
 307973,
 320499,
 321724,
 328777,
 329073,
 330443,
 331639,
 331792,
 334630,
 347588,
 347681,
 354601,
 358462,
 358898,
 371679,
 378639,
 380290,
 381979,
 385573,
 387214,
 388946,
 394052,
 419206,
 423908,
 446450,
 448830,
 452797,
 455586,
 459239,
 464024,
 466635,
 466894,
 478383,
 483285,
 488343,
 489557,
 494757,
 499076,
 499414,
 504683,
 510714,
 514283,
 522610,
 523900,
 527775,
 530133,
 539098,
 542288,
 545714,
 551348,
 551967,
 553192,
 558229,
 564261,
 564416,
 584242,
 589176,
 589191,
 590546,
 592965,
 594388,
 600869,
 612413,
 613509,
 622346,
 663043,
 666973,
 694515,
 719679,
 719758,
 725081,
 739130,
 741292,
 745847,
 762132,
 787727,
 790325,
 790475,
 790778,
 794108,
 794929,
 796683,
 800139,
 807973,
 841571,
 842540,
 842865,
 853039,
 861566,
 863628,
 868212,
 874255,
 926925,
 944199,
 946365,
 947393,
 947665,
 959400,
 961852,
 966139,
 991174,
 993229,
 1016190,
 1023331,
 1028164,
 1042968,
 1055122,
 1062826,
 1067287,
 1100006,
 1101683,
 1122006,
 1128721,
 1147889,
 1161699,
 1170265,
 1174838,
 1201804,
 1246516,
 1252496,
 1255906,
 1261744,
 1265828,
 1281769,
 1285321,
 1298916,
 1303454,
 1310284,
 1325713,
 1334159,
 1341765,
 1375771,
 1380429,
 1383733,
 1387926,
 1396578,
 1426327,
 1438272,
 1478663,
 1488898,
 1490406,
 1570297,
 1570829,
 2385,
 2541,
 4137,
 4282,
 4322,
 5619,
 6737,
 7660,
 7734,
 8016,
 8566,
 10250,
 13350,
 13451,
 14865,
 16002,
 16839,
 17651,
 18881,
 19316,
 19476,
 20371,
 20942,
 21118,
 21234,
 21291,
 22130,
 22424,
 23895,
 24583,
 25627,
 26383,
 26628,
 26662,
 27533,
 27760,
 28380,
 28535,
 30224,
 30801,
 31708,
 32510,
 32528,
 33020,
 33285,
 33873,
 35179,
 35223,
 35325,
 35347,
 35567,
 36045,
 36433,
 37129,
 37941,
 39544,
 44097,
 44779,
 45231,
 46254,
 46972,
 47567,
 47754,
 48568,
 50772,
 57159,
 61061,
 61444,
 61514,
 61873,
 63033,
 63977,
 64735,
 65595,
 66482,
 69003,
 69310,
 69635,
 70568,
 70743,
 71400,
 73024,
 73619,
 74286,
 74353,
 74547,
 76240,
 76936,
 77249,
 78948,
 79736,
 81444,
 82517,
 82626,
 83438,
 85748,
 86244,
 89060,
 90526,
 90701,
 93727,
 94137,
 95234,
 97047,
 98044,
 98248,
 98760,
 99428,
 99460,
 99850,
 100530,
 101458,
 101473,
 101986,
 102343,
 102545,
 102964,
 104160,
 104268,
 105299,
 105807,
 106316,
 109306,
 110929,
 111085,
 114412,
 115663,
 117235,
 117492,
 118255,
 121184,
 123337,
 124571,
 125656,
 128599,
 128871,
 129661,
 133540,
 135971,
 139413,
 139649,
 139797,
 141692,
 144262,
 144638,
 145263,
 146654,
 151697,
 152893,
 153677,
 154869,
 156531,
 156753,
 156780,
 157352,
 158921,
 159116,
 159896,
 161890,
 162236,
 162827,
 162849,
 162937,
 163049,
 164403,
 164654,
 166005,
 167056,
 172982,
 174382,
 174824,
 180153,
 183720,
 188095,
 188805,
 190702,
 191229,
 193531,
 193937,
 199759,
 199829,
 200073,
 200456,
 204622,
 205193,
 205767,
 208261,
 208749,
 209951,
 211459,
 211744,
 212014,
 214903,
 215116,
 215253,
 219433,
 220957,
 221372,
 226710,
 229145,
 229362,
 229749,
 230886,
 231428,
 237598,
 241801,
 242289,
 249110,
 251018,
 252046,
 253956,
 255382,
 262362,
 284075,
 295352,
 300175,
 307782,
 311570,
 313173,
 314759,
 315793,
 319861,
 320909,
 324304,
 329478,
 330755,
 334880,
 335829,
 342253,
 349164,
 353727,
 354577,
 355212,
 359590,
 360131,
 363320,
 377068,
 381721,
 387099,
 388035,
 389881,
 390075,
 399203,
 405219,
 409458,
 422115,
 423539,
 423652,
 432754,
 435704,
 438439,
 452621,
 469319,
 472223,
 472682,
 473005,
 479086,
 484494,
 492458,
 496636,
 505869,
 508477,
 520917,
 524682,
 525985,
 530083,
 534681,
 540849,
 547813,
 559283,
 572896,
 575200,
 577416,
 586858,
 595770,
 604169,
 613132,
 618119,
 629810,
 631132,
 632080,
 633252,
 643875,
 645694,
 661302,
 666344,
 678828,
 680803,
 684485,
 688008,
 688469,
 707734,
 712568,
 714134,
 716411,
 729168,
 731821,
 736965,
 742713,
 746600,
 746867,
 760775,
 761078,
 762193,
 764851,
 765224,
 766556,
 780793,
 789869,
 796483,
 804003,
 805525,
 809147,
 815455,
 817922,
 829556,
 830147,
 834776,
 850823,
 864471,
 876802,
 879074,
 882785,
 902153,
 908361,
 917564,
 919655,
 930708,
 951616,
 952195,
 959740,
 985120,
 985720,
 1005780,
 1022429,
 1048126,
 1053403,
 1067619,
 1093459,
 1099192,
 1105681,
 1122419,
 1139588,
 1147252,
 1149966,
 1157088,
 1158228,
 1189441,
 1197376,
 1245603,
 1254381,
 1260001,
 1264164,
 1282859,
 1285546,
 1301083,
 1315804,
 1332434,
 1371480,
 1384959,
 1391182,
 1414532,
 1416273,
 1423978,
 1451077,
 1460885,
 1500980,
 1504212,
 1509936,
 1512253,
 1513508,
 1528369,
 1540171,
 1562392,
 132,
 2604,
 3563,
 3701,
 3757,
 5698,
 6576,
 6670,
 12160,
 13300,
 15208,
 15707,
 17684,
 17928,
 18542,
 18653,
 21146,
 21224,
 21679,
 23200,
 23631,
 25475,
 26332,
 27344,
 27461,
 27562,
 27939,
 28097,
 29107,
 31337,
 32767,
 32920,
 33718,
 34432,
 34757,
 35069,
 35274,
 36327,
 38507,
 41851,
 42317,
 42645,
 44150,
 45407,
 51436,
 52963,
 54796,
 56966,
 57405,
 58774,
 59611,
 61175,
 63292,
 63423,
 63864,
 64273,
 64360,
 65188,
 67239,
 68032,
 70608,
 70725,
 71882,
 71982,
 72835,
 74325,
 76190,
 77454,
 77967,
 79016,
 79650,
 81422,
 81563,
 82934,
 83584,
 84602,
 84884,
 85293,
 88770,
 89912,
 91240,
 92609,
 93879,
 95897,
 95922,
 96352,
 96835,
 96965,
 97549,
 101542,
 101838,
 103166,
 103473,
 104124,
 104350,
 105774,
 106017,
 106668,
 109075,
 111100,
 112034,
 114406,
 116155,
 116839,
 117067,
 117716,
 121235,
 121685,
 121884,
 122257,
 122436,
 122494,
 123894,
 129044,
 133104,
 134012,
 134599,
 136917,
 139151,
 139447,
 141487,
 142536,
 143644,
 144090,
 144915,
 147455,
 148957,
 149547,
 150249,
 150268,
 150664,
 151364,
 154828,
 154997,
 155625,
 161211,
 161314,
 161508,
 162573,
 163083,
 164095,
 168841,
 168906,
 169381,
 169584,
 175295,
 175472,
 177071,
 178034,
 178415,
 178925,
 179237,
 180466,
 182621,
 182908,
 186050,
 186585,
 189614,
 190124,
 192821,
 196235,
 196402,
 199860,
 202354,
 205181,
 205527,
 207899,
 214947,
 225320,
 225957,
 229175,
 229242,
 229670,
 230964,
 234322,
 238489,
 238574,
 239964,
 240727,
 242809,
 249689,
 256654,
 257702,
 259133,
 259605,
 260698,
 266382,
 266769,
 267258,
 287983,
 296327,
 300484,
 302041,
 307386,
 314180,
 314412,
 314987,
 318582,
 318640,
 323457,
 331538,
 331813,
 332455,
 332466,
 335565,
 357828,
 359583,
 360476,
 361870,
 364443,
 365818,
 372765,
 374655,
 376833,
 379932,
 381068,
 381432,
 381435,
 386364,
 387890,
 396775,
 404608,
 410168,
 415767,
 417819,
 421577,
 428366,
 434695,
 437905,
 438413,
 440753,
 441811,
 442319,
 443654,
 447373,
 455111,
 457535,
 465720,
 468647,
 470350,
 471949,
 472014,
 477238,
 488932,
 493594,
 496575,
 497456,
 515957,
 516377,
 520615,
 525871,
 527571,
 530483,
 531490,
 538245,
 540852,
 541300,
 544212,
 548615,
 576376,
 591070,
 602307,
 603704,
 609710,
 612525,
 612731,
 620852,
 627379,
 644442,
 660382,
 664169,
 675591,
 677808,
 684987,
 708054,
 709431,
 719189,
 722311,
 723193,
 734664,
 736822,
 742796,
 745177,
 756963,
 804294,
 814613,
 828007,
 865871,
 867089,
 868740,
 872447,
 877048,
 891968,
 901399,
 901854,
 902999,
 904597,
 924556,
 943628,
 949277,
 954352,
 970601,
 976330,
 994548,
 1013347,
 1017651,
 1022968,
 1024199,
 1033619,
 1036542,
 1052695,
 1072787,
 1073274,
 1093052,
 1094963,
 1109305,
 1110101,
 1124815,
 1133144,
 1155014,
 1161602,
 1198995,
 1209220,
 1229965,
 1245396,
 1253442,
 1314165,
 1318169,
 1328862,
 1337714,
 1362285,
 1373070,
 1385710,
 1386729,
 1442943,
 1444946,
 1447341,
 1460493,
 1460853,
 1486536,
 1500458,
 1525044,
 1536900,
 1541040,
 1551351,
 1568410,
 2980,
 3285,
 5705,
 6589,
 11935,
 13267,
 15530,
 17027,
 17877,
 18025,
 19828,
 20742,
 20973,
 21954,
 25942,
 27426,
 28147,
 28243,
 28353,
 28937,
 ...]

In [30]:
dfFiltered = dfRatings[dfRatings.master_id.isin(master_idList)]
dfFiltered

             user_id  master_id  rating
224          DarreLP      35929       4
266     SchusterBach     152403       5
304     SchusterBach      91540       5
315     SchusterBach      35564       5
325     SchusterBach     111605       5
340     SchusterBach      74349       5
341     SchusterBach      74349       5
347     SchusterBach     338291       5
352     SchusterBach      12635       5
366     SchusterBach     152403       5
404     SchusterBach      91540       5
415     SchusterBach      35564       5
425     SchusterBach     111605       5
440     SchusterBach      74349       5
441     SchusterBach      74349       5
447     SchusterBach     338291       5
452     SchusterBach      12635       5
455     SchusterBach      88488       5
457     SchusterBach     127988       5
458     SchusterBach     384044       5
459     SchusterBach     105960       5
474     SchusterBach     115701       5
483     SchusterBach     214790       5
494     SchusterBach     737840       5
527     SchusterBach     333947       5
531     SchusterBach      58518       5
532     SchusterBach      62657       5
536     SchusterBach      87033       5
548     SchusterBach      44784       5
550     SchusterBach     103737       5
...              ...        ...     ...
377694   Showbiz_Kid    1543177       4
377738   Showbiz_Kid    1244164       4
377776   Showbiz_Kid     579392       4
377798   Showbiz_Kid     565399       4
377843   Showbiz_Kid     860115       4
377890   Showbiz_Kid    1100941       4
377978   Showbiz_Kid     395082       4
378209   Showbiz_Kid     188187       4
378242   Showbiz_Kid     572630       4
378271   Showbiz_Kid     526426       4
378274   Showbiz_Kid     863014       4
378288   Showbiz_Kid    1224331       4
378379   Showbiz_Kid     176583       4
378664   Showbiz_Kid     461587       4
378665   Showbiz_Kid     461587       4
378745   Showbiz_Kid     167169       4
378768   Showbiz_Kid     296573       4
378804   Showbiz_Kid     806515       4
378862   Showbiz_Kid    1200881       3
378935   Showbiz_Kid    1353084       3
379017   Showbiz_Kid     463817       3
379075   Showbiz_Kid     339993       3
379089   Showbiz_Kid     713516       3
379125   Showbiz_Kid    1012338       3
379277   Showbiz_Kid     612086       3
379324   Showbiz_Kid     779232       3
379605   Showbiz_Kid    1283242       3
379679   Showbiz_Kid     626966       3
379716   Showbiz_Kid     105143       3
379717   Showbiz_Kid     105143       3

[15850 rows x 3 columns]

<p>Mostramos la cantidad de votos que tienen las publicaciones</p>

In [31]:
dfCounts = dfFiltered.groupby(["master_id"]).agg("size").to_frame('count').reset_index()
dfCounts

       master_id  count
0            132      1
1            164      1
2            165      5
3            210      2
4            211      1
5            214      3
6            229      1
7            237      4
8            251      1
9            253      1
10           254      1
11           276      1
12           306      3
13           354      1
14           399      1
15           408      1
16           421      1
17           478      1
18           487      1
19           535      2
20           592      1
21           644      4
22           647      1
23           652      2
24           675      1
25           677      1
26           694      1
27           706      2
28           735      1
29           765      2
...          ...    ...
11376    1543726      1
11377    1544066      2
11378    1544321      1
11379    1544555      1
11380    1546253      1
11381    1546397      1
11382    1546673      1
11383    1547117      1
11384    1547142      1
11385    1547589      1
11386    1548087      1
11387    1548151      1
11388    1549100      1
11389    1550869      1
11390    1551102      1
11391    1553901      1
11392    1554260      2
11393    1555756      2
11394    1556301      1
11395    1558708      1
11396    1558715      1
11397    1560648      1
11398    1563979      1
11399    1565358      1
11400    1566136      1
11401    1566743      1
11402    1568675      1
11403    1568811      1
11404    1569007      1
11405    1571634      2

[11406 rows x 2 columns]

<p>Ordenamos para ver cuales son las 20 publicaciones m√°s veces valoradas.</p>

In [32]:
dfCounts.sort_values("count", ascending=False).head(20)

      master_id  count
61         1355     17
1230      24432     13
487        8408     12
203        3534     11
1833      35527     10
1032      20755      9
211        3636      9
9305     560161      9
738       14557      8
3014      63993      8
252        4046      8
136        2507      8
2938      62111      8
6626     214423      7
3598      81214      7
6000     171075      7
253        4047      7
1184      23605      7
6293     190219      7
1370      27566      7

<p>Calculamos la media de las votaciones</p>

In [33]:
dfMean = dfFiltered.groupby(["master_id"]).agg("mean")
dfMean

           rating
master_id
132          4.00
164          5.00
165          4.20
210          4.50
211          5.00
214          5.00
229          5.00
237          4.75
251          4.00
253          5.00
254          5.00
276          5.00
306          4.00
354          4.00
399          4.00
408          4.00
421          4.00
478          4.00
487          4.00
535          4.00
592          4.00
644          4.50
647          4.00
652          4.50
675          4.00
677          2.00
694          4.00
706          4.50
735          3.00
765          4.00
...           ...
1543726      3.00
1544066      5.00
1544321      2.00
1544555      2.00
1546253      3.00
1546397      3.00
1546673      5.00
1547117      4.00
1547142      5.00
1547589      4.00
1548087      4.00
1548151      5.00
1549100      4.00
1550869      5.00
1551102      2.00
1553901      4.00
1554260      3.50
1555756      4.00
1556301      3.00
1558708      4.00
1558715      5.00
1560648      2.00
1563979      4.00
1565358      5.00
1566136      3.00
1566743      5.00
1568675      3.00
1568811      5.00
1569007      4.00
1571634      5.00

[11406 rows x 1 columns]

<p>Creamos el archivo con ratings filtrado.</p>

In [35]:
dfFiltered.to_csv(path_or_buf = "../TFM Files/usernameRatingsFiltered.csv" , index=False)

<p>Tambi√©n creamos un csv con la relaci√≥n entre id y nombre de las publicaciones.</p>

<p>Primero ponemos en com√∫n los ids de los que tenemos ratings.</p>

In [41]:
master_idRatedList = dfFiltered.drop_duplicates("master_id")

master_idRatedList = master_idRatedList["master_id"].tolist()
master_idRatedList

[35929,
 152403,
 91540,
 35564,
 111605,
 74349,
 338291,
 12635,
 88488,
 127988,
 384044,
 105960,
 115701,
 214790,
 737840,
 333947,
 58518,
 62657,
 87033,
 44784,
 103737,
 61473,
 135184,
 34019,
 478965,
 338321,
 364564,
 478972,
 475202,
 255408,
 548724,
 338279,
 338300,
 933215,
 69485,
 39438,
 1309328,
 36695,
 44316,
 53704,
 39519,
 55305,
 207275,
 131147,
 109798,
 65279,
 132413,
 369197,
 50283,
 78879,
 69034,
 59158,
 120690,
 63864,
 64027,
 55650,
 118980,
 63589,
 89130,
 94329,
 219751,
 14270,
 188819,
 38806,
 32911,
 90059,
 35734,
 80639,
 80959,
 106504,
 644,
 1225128,
 1168321,
 32369,
 181835,
 69320,
 63845,
 106607,
 183720,
 636215,
 291807,
 2565,
 301224,
 2556,
 226702,
 167682,
 446260,
 80227,
 14112,
 249257,
 42751,
 388311,
 140446,
 99142,
 71215,
 157822,
 78987,
 1949,
 50089,
 98900,
 32728,
 39329,
 809481,
 101318,
 190120,
 38743,
 70770,
 580465,
 101492,
 101128,
 63224,
 935190,
 118623,
 185791,
 575485,
 502212,
 65113,
 1216575,
 86321,
 62722,
 195695,
 66651,
 209086,
 928397,
 348456,
 555470,
 44125,
 73016,
 124925,
 204299,
 1445231,
 564746,
 194210,
 1300630,
 554699,
 882950,
 63279,
 154249,
 2090,
 33739,
 77153,
 46798,
 173072,
 59157,
 522602,
 22788,
 293213,
 156753,
 4989,
 95548,
 132414,
 229232,
 179821,
 28403,
 43152,
 160627,
 111957,
 57129,
 90500,
 161556,
 197456,
 126761,
 46538,
 33462,
 67682,
 57162,
 35427,
 90215,
 5984,
 48948,
 53993,
 81872,
 71672,
 112799,
 58639,
 406615,
 35141,
 44418,
 144881,
 111977,
 254600,
 67546,
 77245,
 156104,
 128370,
 32219,
 33985,
 23605,
 81214,
 22684,
 126423,
 96837,
 126257,
 24580,
 160369,
 4425,
 37205,
 494960,
 95594,
 461435,
 1695,
 231959,
 59750,
 40406,
 205193,
 80673,
 379821,
 50671,
 162581,
 46522,
 113313,
 383516,
 393057,
 340898,
 1127802,
 190428,
 3668,
 122247,
 23427,
 58682,
 47059,
 756345,
 38018,
 530404,
 77407,
 350654,
 316723,
 115085,
 30422,
 409378,
 113076,
 435477,
 86612,
 69234,
 57418,
 83032,
 415596,
 30566,
 4487,
 237406,
 67728,
 69536,
 137605,
 32036,
 28812,
 1692,
 41060,
 27450,
 626087,
 48848,
 19753,
 48527,
 57952,
 114202,
 175875,
 26958,
 62146,
 193270,
 387820,
 50027,
 2461,
 177505,
 208865,
 104863,
 141227,
 346932,
 236930,
 5303,
 164693,
 152655,
 232559,
 1368337,
 35481,
 48721,
 98796,
 93244,
 97145,
 27679,
 29228,
 305539,
 335379,
 1456408,
 7142,
 1316543,
 165,
 115017,
 9887,
 326788,
 3685,
 115624,
 11432,
 84253,
 56036,
 107984,
 65325,
 155389,
 207346,
 28053,
 196033,
 53505,
 76174,
 43311,
 81377,
 112862,
 20973,
 1247729,
 20977,
 10510,
 187296,
 423008,
 28544,
 25559,
 496283,
 1286649,
 178137,
 297612,
 16203,
 30784,
 174811,
 43201,
 38637,
 127866,
 351338,
 117208,
 260575,
 202539,
 4955,
 59496,
 43709,
 489403,
 113243,
 109426,
 785879,
 214705,
 21291,
 404800,
 20755,
 48487,
 33278,
 160361,
 122590,
 52668,
 3342,
 33027,
 469403,
 140631,
 42494,
 66914,
 45245,
 93573,
 30398,
 21222,
 30845,
 159277,
 132817,
 205518,
 4515,
 34129,
 310119,
 1120175,
 130254,
 29712,
 139000,
 209064,
 168906,
 64718,
 345879,
 304581,
 241245,
 4446,
 4282,
 107752,
 35925,
 13142,
 52675,
 85022,
 63365,
 69251,
 414937,
 414924,
 505930,
 437420,
 98895,
 177839,
 34124,
 85917,
 28483,
 43776,
 24482,
 572533,
 31820,
 70518,
 23911,
 39538,
 36427,
 337267,
 170274,
 115745,
 413219,
 148302,
 406702,
 18500,
 142447,
 90322,
 20832,
 122483,
 193582,
 39772,
 18021,
 141329,
 26274,
 126582,
 46613,
 37942,
 194458,
 28759,
 6551,
 89727,
 25796,
 25794,
 138436,
 58956,
 106445,
 101181,
 245589,
 37191,
 225659,
 119044,
 122905,
 428749,
 20121,
 2598,
 66584,
 45184,
 35903,
 46330,
 17591,
 874144,
 292799,
 28418,
 29433,
 212973,
 466980,
 54621,
 30485,
 3983,
 19038,
 52383,
 164983,
 838618,
 1253356,
 11409,
 90206,
 28268,
 739045,
 4160,
 3683,
 412319,
 2085,
 546407,
 2546,
 155386,
 38060,
 136282,
 112271,
 229175,
 26126,
 118642,
 700188,
 946116,
 413326,
 47332,
 98903,
 115320,
 48869,
 80232,
 144364,
 128268,
 259347,
 255309,
 2614,
 215719,
 65676,
 55055,
 41952,
 19007,
 58951,
 346504,
 46896,
 5055,
 28394,
 3701,
 537930,
 12296,
 5603,
 97138,
 124609,
 1163349,
 64072,
 106804,
 24312,
 393447,
 40522,
 17517,
 121235,
 136375,
 121243,
 121234,
 4276,
 50622,
 58455,
 203739,
 3224,
 33756,
 56437,
 422713,
 198507,
 198411,
 56634,
 4722,
 400768,
 371079,
 70748,
 59367,
 143493,
 31211,
 386753,
 93247,
 152340,
 266198,
 25274,
 23943,
 22163,
 71676,
 30029,
 122104,
 78691,
 90968,
 34177,
 261818,
 105605,
 284594,
 29211,
 76425,
 57743,
 49948,
 53956,
 750354,
 1160,
 130322,
 30524,
 31315,
 63364,
 83335,
 49246,
 60972,
 1517,
 11812,
 133927,
 12905,
 568406,
 1139784,
 901707,
 952529,
 168329,
 1151529,
 174924,
 701573,
 1430019,
 551200,
 382070,
 1517215,
 551161,
 553637,
 115919,
 310868,
 380811,
 178639,
 1298276,
 1052292,
 1200453,
 1167846,
 557081,
 94972,
 451966,
 1054201,
 1231039,
 1067516,
 599996,
 701151,
 556778,
 1385917,
 171952,
 105350,
 363284,
 557711,
 497305,
 669717,
 551004,
 1138302,
 1256800,
 1276947,
 1437681,
 1244164,
 970636,
 696195,
 585467,
 1453021,
 1212992,
 395472,
 185342,
 229952,
 151639,
 853977,
 1540694,
 1020447,
 551666,
 1232997,
 1310284,
 1543726,
 31381,
 654102,
 707781,
 326223,
 223383,
 686731,
 1432764,
 178130,
 429942,
 1315584,
 247226,
 408072,
 72009,
 27722,
 373240,
 1061996,
 158106,
 123166,
 500183,
 1406908,
 1118721,
 1525458,
 728261,
 405012,
 708692,
 836321,
 467563,
 918590,
 643978,
 974313,
 1050577,
 75241,
 110449,
 14557,
 3762,
 27539,
 12214,
 29647,
 116530,
 136749,
 175355,
 143997,
 40703,
 75681,
 20910,
 30085,
 120358,
 689409,
 70993,
 52822,
 91917,
 88005,
 228889,
 107597,
 112747,
 98715,
 32621,
 26286,
 427886,
 99666,
 357158,
 232370,
 441811,
 128325,
 94796,
 6760,
 155540,
 34209,
 90423,
 854342,
 724630,
 604694,
 887091,
 81399,
 50569,
 542044,
 199753,
 401157,
 47256,
 531381,
 402990,
 846836,
 111732,
 1254674,
 551528,
 718985,
 686544,
 209457,
 1371182,
 1070847,
 416933,
 142429,
 1014157,
 249132,
 484294,
 481334,
 116186,
 418269,
 1161602,
 249515,
 455109,
 86127,
 479283,
 1484891,
 132946,
 540994,
 57665,
 9087,
 408662,
 564347,
 425474,
 404890,
 401162,
 856041,
 466678,
 1400617,
 84699,
 469057,
 499964,
 710425,
 876861,
 433107,
 416831,
 385496,
 575135,
 475934,
 1450437,
 637654,
 97080,
 854464,
 399637,
 648628,
 86609,
 62111,
 873452,
 262006,
 204063,
 470173,
 71802,
 1068404,
 728525,
 735134,
 199532,
 1186956,
 9142,
 74540,
 1170126,
 28845,
 171346,
 749550,
 2102,
 642609,
 640693,
 38871,
 685664,
 29006,
 744031,
 56303,
 61131,
 650084,
 121919,
 203647,
 60289,
 1260601,
 75547,
 116080,
 223676,
 1374987,
 417055,
 314507,
 8912,
 229737,
 400040,
 19828,
 569011,
 283237,
 793446,
 296573,
 1299637,
 1452535,
 721120,
 1523946,
 904983,
 177206,
 310987,
 870941,
 99378,
 773230,
 554171,
 583259,
 459205,
 833012,
 1043063,
 624643,
 396589,
 770413,
 1214156,
 563171,
 640406,
 1336750,
 544297,
 944432,
 359744,
 457298,
 810914,
 380938,
 1544321,
 142156,
 1335980,
 1034156,
 1515738,
 830458,
 1109627,
 1288935,
 1263041,
 1295411,
 27566,
 79646,
 73532,
 48472,
 435403,
 114413,
 560161,
 152261,
 29171,
 938343,
 276524,
 30231,
 298924,
 63446,
 176070,
 176823,
 418131,
 1152714,
 60977,
 71642,
 1035045,
 716627,
 621396,
 890425,
 369155,
 379706,
 750121,
 384683,
 227076,
 494778,
 641178,
 101972,
 424574,
 507331,
 99902,
 1249321,
 44541,
 189298,
 13838,
 466473,
 160319,
 339631,
 339643,
 11397,
 22168,
 726030,
 726029,
 425715,
 166931,
 54858,
 1285800,
 296571,
 368825,
 117389,
 830991,
 67453,
 27541,
 426643,
 230855,
 530615,
 162790,
 223802,
 76952,
 30783,
 136950,
 28027,
 6116,
 96794,
 416309,
 583469,
 932565,
 373907,
 426453,
 139466,
 214273,
 536140,
 94804,
 23336,
 440730,
 74324,
 6424,
 936516,
 580473,
 122876,
 234593,
 70096,
 746798,
 32706,
 20240,
 385842,
 249712,
 826783,
 1104620,
 70575,
 70582,
 16824,
 551348,
 503355,
 25793,
 33204,
 33203,
 468965,
 364712,
 98050,
 925207,
 405110,
 354241,
 462732,
 100115,
 159076,
 796628,
 1242961,
 213129,
 41244,
 229376,
 211793,
 887378,
 409838,
 46343,
 1366829,
 590066,
 490618,
 4264,
 66780,
 552464,
 136142,
 1531779,
 162221,
 1074988,
 8718,
 30882,
 4565,
 188468,
 224453,
 148901,
 1027464,
 926539,
 358922,
 118625,
 245910,
 1352467,
 190555,
 1279054,
 814670,
 105553,
 371686,
 826708,
 413511,
 62232,
 401660,
 138327,
 613725,
 571139,
 7944,
 122614,
 81267,
 659536,
 1506290,
 607841,
 41700,
 549773,
 37078,
 105777,
 353091,
 ...]

In [42]:
dfFilteredScaledData = scaledData[scaledData.master_id.isin(master_idRatedList)]
dfFilteredScaledData

,master_id,scaledFeatures,title
7,94241,"{'type': 1, 'values': [0.10568112353641101, -0...","Chicas, Chicas, Chicas"
11,98999,"{'type': 1, 'values': [0.138029771330567, -0.7...",Somebody
18,103368,"{'type': 1, 'values': [0.050226298746430004, -...",Rusty Acid
19,105384,"{'type': 1, 'values': [0.08719618193975001, -0...",Morning Light
20,106899,"{'type': 1, 'values': [0.10568112353641101, 0....",The Misery Index: Notes From The Plague Years
24,115085,"{'type': 1, 'values': [0.14265100672973202, -0...",Reveraze / Sleeping Beauty
38,129229,"{'type': 1, 'values': [0.133408535931401, 0.80...",Rip It!
43,133087,"{'type': 1, 'values': [0.14265100672973202, 0....",Ao Vivo
44,133961,"{'type': 1, 'values': [0.138029771330567, 0.34...",Numa Records Year 1
61,162885,"{'type': 1, 'values': [0.09643865273808101, 0....",Alive And Screamin'
73,185256,"{'type': 1, 'values': [0.14265100672973202, 0....",Master Mixes
85,204063,"{'type': 1, 'values': [0.027120121750604003, 0...",The Very Best Of Enya
92,216312,"{'type': 1, 'values': [0.073332475742255, -0.4...",Ricky Sings Again
101,237609,"{'type': 1, 'values': [0.10568112353641101, -0...",Crystal Frontier
102,242268,"{'type': 1, 'values': [0.128787300532236, -0.3...",Cold Shot!
130,358898,"{'type': 1, 'values': [0.050226298746430004, -...",Show Face
135,385573,"{'type': 1, 'values': [0.036362592548934, -0.9...",Cyanid
155,499414,"{'type': 1, 'values': [0.133408535931401, 0.22...",Tapestry Revisited: A Tribute To Carole King
166,551348,"{'type': 1, 'values': [0.147272242128897, 0.58...",Italian Hip Hop Story
169,558229,"{'type': 1, 'values': [0.07795371114142001, -0...",Animal Zoo / Red Light Roll On
175,590546,"{'type': 1, 'values': [0.082574946540585, -0.9...",Memory Of A Free Festival
176,592965,"{'type': 1, 'values': [0.082574946540585, -0.8...",Livin' In A Back Street
183,666973,"{'type': 1, 'values': [0.133408535931401, -0.8...",Take The Money And Run
194,790475,"{'type': 1, 'values': [0.013256415553109002, -...",Life
197,794929,"{'type': 1, 'values': [0.15651471292722702, 2....",The Best Of Cerrone Productions
226,1100006,"{'type': 1, 'values': [0.06871124034309001, 0....",Polnareff
244,1310284,"{'type': 1, 'values': [-0.023713467640211, -0....",Symphonie Op. 20 √¢‚Ç¨¬¢ Viviane Op. 5
248,1375771,"{'type': 1, 'values': [0.027120121750604003, -...",Wonderland (The Remixes)
249,1380429,"{'type': 1, 'values': [0.082574946540585, 0.84...",My American Dream
252,1396578,"{'type': 1, 'values': [0.004013944754779, -0.8...",Sign√É¬© Cat's Eyes
...,...,...,...
69799,696195,"{'type': 1, 'values': [0.11030235893557601, -0...",Leakage
69800,699784,"{'type': 1, 'values': [0.15651471292722702, -0...",Dream #2
69804,750121,"{'type': 1, 'values': [0.045605063347265, -0.1...",Catching On
69809,778410,"{'type': 1, 'values': [0.091817417338916, 0.34...",Miss Fortune
69822,912989,"{'type': 1, 'values': [0.16113594832639203, 0....",Moment To Moment
69824,932327,"{'type': 1, 'values': [0.15651471292722702, -0...",Pour Les Amants
69835,1034837,"{'type': 1, 'values': [0.133408535931401, -0.8...",Todo Lo Que Quiero
69846,1112346,"{'type': 1, 'values': [0.124166065133071, -0.8...",Daddy Number Two
69854,1196007,"{'type': 1, 'values': [0.022498886351439002, -...",The Gold & Silver Gala
69886,12635,"{'type': 1, 'values': [0.08719618193975001, 1....",Code Red
69888,15201,"{'type': 1, 'values': [0.133408535931401, -0.3...",Maximum Priest E.P.
69893,17437,"{'type': 1, 'values': [0.133408535931401, -0.5...",Sex On Wheelz
69894,17841,"{'type': 1, 'values': [0.124166065133071, -0.8...",How Long
69897,19459,"{'type': 1, 'values': [0.133408535931401, -0.1...",Fall
69903,26677,"{'type': 1, 'values': [0.07795371114142001, -0...",Genesis
69906,30499,"{'type': 1, 'values': [0.124166065133071, -0.0...","Three Parts To My Soul (Spiritus, Manes Et Umbra)"
69907,30645,"{'type': 1, 'values': [0.101059888137246, -0.7...",Train Track 2002 / Tonic
69913,37412,"{'type': 1, 'values': [0.138029771330567, 2.72...",After Trance Vol. 2 (Techno Morning Mix Party)
69920,44477,"{'type': 1, 'values': [0.10568112353641101, 0....",Passion And Warfare
69923,48434,"{'type': 1, 'values': [0.128787300532236, 1.04...",Danse Macabre Sampler Part I
69924,48520,"{'type': 1, 'values': [0.101059888137246, -0.0...",In√É¬©dits 1970
69926,50593,"{'type': 1, 'values': [0.138029771330567, -0.6...",Fashion Slam
69927,51260,"{'type': 1, 'values': [0.138029771330567, -0.8...",It's Nasty
69930,53185,"{'type': 1, 'values': [0.133408535931401, -0.7...",A Little Less Conversation
69933,55948,"{'type': 1, 'values': [0.091817417338916, -0.7...",The Grand Hour
69938,62007,"{'type': 1, 'values': [0.124166065133071, -0.4...",Plutonium
69939,62374,"{'type': 1, 'values': [0.133408535931401, -0.2...",Omen III (Remixes)
69940,65279,"{'type': 1, 'values': [0.082574946540585, -0.8...",Him Or Me
69942,67705,"{'type': 1, 'values': [0.133408535931401, -0.2...",Guantanamera
69949,76795,"{'type': 1, 'values': [0.128787300532236, -0.8...",Let Go The Line

<p>Finalmente, guardamos: </p>

1. una tabla con la relaci√≥n entre ids y nombre de la publicaci√≥n.
2. La tabla con los datos filtrada con los ids de las publicaciones de las que disponemos ratings.

In [48]:
dfFilteredScaledData[['master_id','title']].to_csv(path_or_buf = "../TFM Files/idTitleList.csv" , index=False)

In [47]:
dfFilteredScaledData.to_json(path_or_buf = "../TFM Files/dataScaledFiltered.json", orient='records', lines=True)